Implement undefined method in Encoding class
smalot/pdfparser pull request #378
Opened 2020-12-23 12:04 UTC by tomlutzenberger

The __toString method was missing/not implemented, even though it is called in some cases.

Fixes #364

2020-12-23 12:35 UTC, k00ni requested changes
@tomlutzenberger Thank you for your contribution!

Can you please fix coding style issues (run `vendor/bin/php-cs-fixer fix`) and add at least one test, which demonstrates the original problem and your fix?

2020-12-23 16:15 UTC, tomlutzenberger commented
I fixed the issues but was not able to even run the existing tests. It seems PHPUnit is not a dependency and is therefore not found in PHPStorm.
Do I miss something here?

2020-12-23 16:24 UTC, k00ni commented
We use `symfony/phpunit-bridge` which allows us to run PHPUnit on PHP 5.6 - 7.4. You can run tests locally by executing `vendor/bin/simple-phpunit`. It will install PHPUnit in a sub-folder and run tests. Might need to set `<env name="SYMFONY_PHPUNIT_VERSION" value="7.5"/>` in `phpunit.xml` though.

2020-12-23 20:41 UTC, tomlutzenberger commented
It's hard to understand the logic in the Font class without any method documentation, especially the character translation and encoding part. Even though I spent almost all day to get the tests up and running, I wasn't able to write a test due to lack of knowledge about the structure of PDF files 😞

2020-12-25 14:13 UTC, k00ni approved these changes
I took the liberty and added a few tests which proof your fix is working. Looks good now. Thank you for your effort.

2020-12-25 14:17 UTC, merged