Refactor: declare pdf whitespaces in global variable to avoid bug
smalot/pdfparser pull request #411
Opened 2021-04-20 03:15 UTC by LucianoHanna

Hi,

I made some refactor in RawDataParser, I declared a global variable containing pdf whitespaces so we don't need to hardcode were use whitespace, avoiding bug if forget to consider all pdf whitespaces

2021-04-20 06:59 UTC, k00ni requested changes
@LucianoHanna thank you for the PR.

I welcome your changes in general but have to ask you to move `$pdfWhitespaces` and `$pdfWhitespacesRegex` to [Config.php](https://github.com/smalot/pdfparser/blob/master/src/Smalot/PdfParser/Config.php). 

Its purpose is to hold default values which can be overridden by the user. In some cases it is required to change a default value because a given set of PDFs require it. [Here](https://github.com/smalot/pdfparser/blob/ce6aa779dd67fadf3887dace6f31ea70882dba73/tests/Integration/ParserTest.php#L271-L282) is a basic example how to setup and use `Config` instance.

2021-04-20 06:59 UTC, k00ni commented on src/Smalot/PdfParser/RawData/RawDataParser.php
> +        //skip initial white space chars
Please add a whitespace before skip.

2021-04-20 06:59 UTC, k00ni commented on src/Smalot/PdfParser/RawData/RawDataParser.php
> +    protected $pdfWhitespaces = "\0\t\n\f\r ";
Please make it a comment as of:

```php
/**
 * Represents: (NUL, HT, LF, FF, CR, SP)
 */
```

2021-04-20 06:59 UTC, k00ni commented on src/Smalot/PdfParser/RawData/RawDataParser.php
>          /*
Add new line in between.

2021-04-20 11:29 UTC, k00ni commented
Another remark: Please create a separate branch when creating a pull request. It limits our options if you push using your `master`.

2021-04-21 06:44 UTC, k00ni requested changes

2021-04-21 06:44 UTC, k00ni commented on src/Smalot/PdfParser/Config.php
> -    public function setPdfWhitespacesRegex(string $pdfWhitespacesRegex): void
We merged in #383 lately, which means we only support 7.1+. Support for earlier PHP versions is not required anymore. I like these explicit return values, can you re-add them please?

2021-04-21 06:52 UTC, k00ni commented on src/Smalot/PdfParser/RawData/RawDataParser.php
> +    }
Can you add `: int` for each function to make return value type more clear?

2021-04-21 06:58 UTC, k00ni commented on src/Smalot/PdfParser/Config.php
> +    private $pdfWhitespacesRegex = '[\0\t\n\f\r ]';
Can you add `@var string` here for both variables too please?

2021-04-21 15:41 UTC, LucianoHanna commented
@k00ni I made these changes but there's one test failing, maybe should open another PR to remove "CI / Tests alternative autoloader (PHP 5.6)"

2021-04-23 07:08 UTC, k00ni commented
#409 already targets the outdated alternative autoloader tests. Can you merge it and try again? In the end I will squash your PR, so it shouldn't matter

2021-04-26 07:03 UTC, k00ni approved these changes
👍🏿

2021-04-26 09:25 UTC, k00ni commented
We had to fix some problems in our testing environment (Github workflow + Scrutinizer). All fixes are now in master. Can you please merge `master` to see if there are any problems left?

2021-04-26 10:02 UTC, LucianoHanna commented
I merged master and everything looks ok but there's nothing left to commit...

2021-04-26 10:59 UTC, k00ni commented
There should be a merge commit to push. Anyway.

2021-04-26 10:59 UTC, merged