Make horizontal offset configurable
smalot/pdfparser pull request #505
Opened 2022-01-08 10:44 UTC by rubenvanerk

Solves the issue as described in this comment: https://github.com/smalot/pdfparser/issues/193#issuecomment-636697897

2022-01-10 14:34 UTC, k00ni requested changes
Thank you!

2022-01-10 14:34 UTC, k00ni commented on src/Smalot/PdfParser/Config.php
> +
Which type is it? string...? Please add `@var` PHPDoc comment.

2022-01-10 14:34 UTC, k00ni commented on src/Smalot/PdfParser/Config.php
> +    public function setHorizontalOffset($value)
Based on the type of the property, use appropriate parameter / return value.

2022-01-10 14:34 UTC, k00ni commented on src/Smalot/PdfParser/PDFObject.php
> +                            $text .= $this->config->getHorizontalOffset();
Can you construct a basic test which includes this change?

2022-01-10 14:36 UTC, k00ni commented
Does this fix #193?

2022-01-17 08:19 UTC, k00ni approved these changes
Thank you for your changes, it looks good to me.

If you have the time can you tell me if this PR fixes #193 and #72?

Any remarks @j0k3r?

2022-01-17 08:31 UTC, rubenvanerk commented
As I don't have access to the pdf's in those issues, I can't say for sure. But I think it does.

Since I used the pdf of #494, I can say that it fixes _that_ issue.

2022-01-17 13:01 UTC, j0k3r approved these changes

2022-01-17 13:04 UTC, merged