Handle null Header and falsy header elements (Fixes #514)
smalot/pdfparser pull request #525
Opened 2022-04-01 10:00 UTC by dsuurlant

**Document.php**
`$object->getHeader()` can be `null` but that is never checked before calling `->get(...)` methods on it. Fixed by adding a `continue` if `getHeader()` returns `null`.

**Header.php**
Header elements may resolve to have `false` as a value (in `ElementDate::parse`, `ElementString::parse` and `ElementName::parse`). Another solution would be to change those `bool` returns to i.e. `ElementNull` or `ElementMissing`, but that seemed too big of a change, so instead I added a check to `Header->get(...)` that returns `ElementMissing` if the value of the Element is falsy (i.e. `null, false, 0, ''` )

This should fix #514 .

2022-04-01 12:10 UTC, j0k3r reviewed
Any chance to add some tests to cover your changes?

2022-04-01 14:11 UTC, dsuurlant commented
Updated the PR:

* Added test for Header->get when an element may be `false` 
* Removed the `null` check on `getHeader()` since it is actually never null -- it's instantiated in the constructor of `PDFObject`. I also updated the property and getter to reflect this.

2022-04-04 10:30 UTC, k00ni commented on src/Smalot/PdfParser/PDFObject.php
> -    public function getHeader(): ?Header
That is an API change and would require us to raise major version of the library. Can you please revert it?

2022-04-22 14:47 UTC, dsuurlant commented
Updated the PR:
* Reverted changes to PDFObject API

2022-04-26 07:55 UTC, k00ni requested changes

2022-04-26 07:55 UTC, k00ni commented on tests/Integration/HeaderTest.php
> +        $this->assertTrue($header->get('SubType') instanceof ElementMissing);
Thank you for your latest changes.

Can you please add a short comment here, which describes what these lines do. I assume you try to exploit the error before but with your patch it works now?

2022-04-29 05:39 UTC, k00ni commented on tests/Integration/HeaderTest.php
> +        $this->assertTrue($header->get('SubType') instanceof ElementMissing);
Yeah, it looks great, go for it.

2022-04-29 09:01 UTC, k00ni commented on tests/Integration/HeaderTest.php
> +        $this->assertTrue($header->get('SubType') instanceof ElementMissing);
You might have to use `/*` instead of `/**`.

2022-04-29 10:50 UTC, k00ni commented
🥳 Looks good to me. I will leave this open until beginning of next week and will merge it, if there are no objections.

Thanks for your work @dsuurlant!

2022-04-29 10:50 UTC, k00ni approved these changes

2022-05-02 06:42 UTC, merged