fix: allow to parse null or empty header element
smalot/pdfparser pull request #560
Opened 2022-11-23 10:07 UTC by DogLoc

## Why I open this pull request ?

When I pass a empty string value at the first arguments of ``parseHeader`` function, it throw an exception :   

``` 
Argument 1 passed to Smalot\PdfParser\Parser::parseHeader() must be of the type array, string given, called in /path/to/project/vendor/smalot/pdfparser/src/Smalot/PdfParser/Parser.php on line 266
```

that append when I provide a PDF like this : [20221025_debug_header_parse.pdf](https://github.com/smalot/pdfparser/files/9868222/20221025_debug_header_parse.pdf)

If it helps, I have already opened a case for this problem. : https://github.com/smalot/pdfparser/issues/557

Have a good day ^^

2022-11-24 08:34 UTC, k00ni requested changes
@DogLoc thank you for this fix. I have a few things:

* [ ] Can you move the new if-clause before the switch-clause? I can not see why this check is only relevant for the `>>` case.
* [ ] Please provide at least one test. If you need help here, let me know.
* [ ] Please fix failing CS workflow by running PHP-CS-Fixer.
* [x] Out of curiosity: why not return `ElementNull` instead? Why do you use `null`?

2022-11-24 14:25 UTC, DogLoc commented
> @DogLoc thank you for this fix. I have a few things:
> 
> * [ ]  Can you move the new if-clause before the switch-clause? I can not see why this check is only relevant for the `>>` case.
> * [ ]  Please provide at least one test. If you need help here, let me know.
> * [ ]  Please fix failing CS workflow by running PHP-CS-Fixer.
> * [ ]  Out of curiosity: why not return `ElementNull` instead? Why do you use `null`?

Finally I use an empty array for input and output (<<, >>) because with the ElementNull class, the code tries to retrieve the header on a null element I don't have strong knowledge of this project, so if you have a better suggestion, I take it! ^^

I have provided a unit test for the parser, let me know if this is sufficient.

2022-11-28 08:30 UTC, DogLoc commented
@k00ni master merged in my branch 👍

2022-12-02 11:13 UTC, k00ni requested changes
Thank you for your changes! There is only one thing and we are good to go.

2022-12-02 13:05 UTC, k00ni commented on src/Smalot/PdfParser/Parser.php
> +        if (('<<' === $type || '>>' === $type) && $valueIsEmpty)) {
```suggestion
        if (('<<' === $type || '>>' === $type) && $valueIsEmpty) {
```
My bad, I missed a `)`.

2022-12-02 13:14 UTC, k00ni commented
Looks good to me. I will merge it next week if there are no objections.

Thank you @DogLoc!

2022-12-02 13:14 UTC, k00ni approved these changes

2022-12-02 14:08 UTC, DogLoc commented
Thanks you too  ^^ ! @k00ni

2022-12-05 14:43 UTC, merged