#561 Added optional getText() argument to return limited number of document pages if set
smalot/pdfparser pull request #562
Opened 2022-11-24 16:07 UTC by alesrebec

Solving #561 
Tested locally and working fine.

2022-11-25 15:39 UTC, k00ni requested changes
@alesrebec thank you for this nice addition.

Please provide at least one test which covers your code.

2022-11-25 15:39 UTC, k00ni commented on src/Smalot/PdfParser/Document.php
> +    public function getText($limit = NULL): string
```suggestion
    public function getText(int|null $pageLimit = null): string
```

2022-11-25 15:39 UTC, k00ni commented on src/Smalot/PdfParser/Document.php
> +        if (!empty($limit) && is_numeric($limit)) {
```suggestion
        if (is_int($pageLimit) && 0 < $pageLimit) {
```

2022-12-13 08:51 UTC, k00ni commented
@alesrebec I took the liberty and finalized the PR. Any remarks?

I will merge it in a couple of days if there are no objections.

2022-12-13 13:48 UTC, alesrebec commented
> @alesrebec I took the liberty and finalized the PR. Any remarks?
> 
> I will merge it in a couple of days if there are no objections.

Thanks for finalizing the PR.
I had some issues running the tests locally when I was about to write the tests and it just slipped from my todo list.
All good with the merge.

2022-12-14 07:24 UTC, k00ni approved these changes

2022-12-16 09:38 UTC, merged